export const REQ_GET_DATES = 'REQ_GET_DATES';
export const RECV_GET_DATES = 'RECV_GET_DATES';
export const XHR_FAIL = 'XHR_FAIL';
export const ADD_NEW_RESERVATION = 'ADD_NEW_RESERVATION';
export const REQ_REMOVE_RESERVATION = 'REQ_REMOVE_RESERVATION';
export const REMOVE_RESERVATION_SUCCESS = 'REMOVE_RESERVATION_SUCCESS';
export const CLEAR_ERROR = 'CLEAR_ERROR';